apiVersion: v1
kind: Service
metadata: 
  name: app-service
  labels: 
    name: app-service
spec:
  type: NodePort
  selector: 
    name: application
  ports: 
    - port: 80
      targetPort: 8000
      nodePort: 30457       
